Create 2 action buttons inside header component
Alex-2kZharkov/oldboy-barbershop pull request #13
Opened 2023-07-26 08:48 UTC by MillanaCh

1. I added new package react-icons in package.json and package-lock.json

2. src folder
- app -> changed global.css
<img width="547" alt="Снимок экрана 2023-07-24 в 7 52 20 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/32936822-8556-4317-bed6-3fcfb2ad397d">

- app -> page.tsx 
<img width="1138" alt="Снимок экрана 2023-07-24 в 7 51 41 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/abebb259-aa0b-485a-bd30-de3f33e12df8">

**app -> components -> features (new folder)**
- features -> header.tsx (create useState for managing the sidebar modal window)
<img width="1110" alt="Снимок экрана 2023-07-24 в 7 52 40 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/8fdac60f-ae79-41ba-be16-f31a2d215d70">

- features -> sidebar.tsx
<img width="1110" alt="Снимок экрана 2023-07-26 в 1 43 51 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/f26d54c3-e666-49d9-b37b-1db4e24a8e75">

- features -> components -> cities.tsx (created another file for cutting out mapped cities and wrap it in useMemo())
<img width="1110" alt="Снимок экрана 2023-07-26 в 1 43 08 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/eb5cd606-937b-4649-aa76-0f7b79bcf888">

- features -> Header.test.tsx (test)
<img width="1110" alt="Снимок экрана 2023-07-24 в 7 52 34 AM" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/93415318/1ab5b0c8-539e-4606-ab75-3211de6899de">

2023-07-27 04:48 UTC, Alinochka07 approved these changes, later dismissed

2023-07-28 06:47 UTC, Alinochka07 approved these changes, later dismissed

2023-07-29 08:47 UTC, Alex-2kZharkov commented
> 1. I added new package react-icons in package.json and package-lock.json
> 2. src folder
> 
> * app -> changed global.css
> 
> <img alt="Снимок экрана 2023-07-24 в 7 52 20 AM" width="547" src="https://user-images.githubusercontent.com/93415318/255629674-32936822-8556-4317-bed6-3fcfb2ad397d.png">
> * app -> page.tsx
> 
> <img alt="Снимок экрана 2023-07-24 в 7 51 41 AM" width="1138" src="https://user-images.githubusercontent.com/93415318/255630365-abebb259-aa0b-485a-bd30-de3f33e12df8.png">
> **app -> components -> features (new folder)**
> 
> * features -> header.tsx (create useState for managing the sidebar modal window)
> 
> <img alt="Снимок экрана 2023-07-24 в 7 52 40 AM" width="1110" src="https://user-images.githubusercontent.com/93415318/255631824-8fdac60f-ae79-41ba-be16-f31a2d215d70.png">
> * features -> sidebar.tsx
> 
> <img alt="Снимок экрана 2023-07-26 в 1 43 51 AM" width="1110" src="https://user-images.githubusercontent.com/93415318/256171593-f26d54c3-e666-49d9-b37b-1db4e24a8e75.png">
> * features -> components -> cities.tsx (created another file for cutting out mapped cities and wrap it in useMemo())
> 
> <img alt="Снимок экрана 2023-07-26 в 1 43 08 AM" width="1110" src="https://user-images.githubusercontent.com/93415318/256171908-eb5cd606-937b-4649-aa76-0f7b79bcf888.png">
> * features -> Header.test.tsx (test)
> 
> <img alt="Снимок экрана 2023-07-24 в 7 52 34 AM" width="1110" src="https://user-images.githubusercontent.com/93415318/255632683-1ab5b0c8-539e-4606-ab75-3211de6899de.png">

I really liked you give such a detailed description. If takes a long time, you can skip screenshots. But still: the description is good. Keep it the same way in future when you work real job

2023-07-29 09:05 UTC, Alex-2kZharkov requested changes

2023-07-29 09:05 UTC, Alex-2kZharkov commented on .eslintrc.json
> +    "no-param-reassign": "off", //did it temporarily
set both of them to `warn` forever

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    userEvent.click(btnRecord);
it is an async thing, use `await userEvent.click`

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    expect(btnRecord).toBeEnabled();
empty line please

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    const btnBuy = screen.getByRole('button', {
use `await findByRole` if this thing should appear after you click on button

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    const btnBuy = screen.getByRole('button', {
+1 empty line.

Overall good tests

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    render(<Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />);
wait a minute. tests for `Sidebar` should be in the `sidebar.test.tsx` file

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    // Search bar
remove comment, no comments for such simple things. You have descriptive `searchBox` variable

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
> +    expect(searchBox).toBeInTheDocument();
+1 empty line

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
you should set correct options in eslintrc, see https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
and remove comment in the end

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
> +  // const handleCityClick = useCallback(
actually, better to uncomment and use it right now with console.log

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
> +          // eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions
I thought we have turned it off in eslintrc , if no, please turn it off

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
index.ts is required in this folder. It is a main rule🙂

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/header.tsx
no-no, it should be `src/features` not `src/components/features`

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/header.tsx
> +export function HeaderPage(): JSX.Element {
arrow function please. It is your default syntax

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/header.tsx
> +      {isOpen ? <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} /> : <div />}
empty div looks really strange, better `isOpen && <Sidebar />`

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/header.tsx
> +          onClick={() => setIsOpen(!isOpen)}
please read this and fix accordingly https://www.delftstack.com/howto/react/react-setstate-prevstate/

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/Header.test.tsx
the component is written in lower case, so this file also `header.test.tsx`

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
create a separate folder `cities` here and put this file there

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/sidebar.tsx
create a separate folder `sidebar` here and put this file there

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/sidebar.tsx
> +interface ModalWindow {
catch you. Why you name if ModalWindow if you apply it to the Sidebar? it should be SidebarProps

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/sidebar.tsx
> +  setIsOpen: (value: boolean) => void;
good usage of TS, keep the good work

2023-07-29 09:05 UTC, Alex-2kZharkov commented on src/components/features/components/cities.tsx
> +export function Location(): ReactElement {
one more time: this component name and file name should match. Currently they do not: `cities.tsx` and `Location`. Please, select one and fix

2023-07-30 11:00 UTC, Alex-2kZharkov submitted a review, later dismissed

2023-07-30 11:00 UTC, Alex-2kZharkov commented on src/Features/sidebar/sidebar.tsx
index.ts for sidebar folder🙂

2023-07-30 11:13 UTC, Alex-2kZharkov submitted a review, later dismissed

2023-08-05 10:02 UTC, Alex-2kZharkov approved these changes

2023-08-05 10:02 UTC, Alex-2kZharkov commented on src/Features/header/header.test.tsx
> +    const btnBuy = screen.getByText('Купить косметику');
should be full name `buttonName` + 1 empty line between expect and `const`

2023-08-05 10:03 UTC, Alex-2kZharkov approved these changes

2023-08-05 10:22 UTC, merged

2023-08-05 10:23 UTC, Alex-2kZharkov approved these changes