Fix/ob-28_load-barbershops-count-from-api
Alex-2kZharkov/oldboy-barbershop pull request #27
Opened 2023-08-23 04:49 UTC by ain-odin

1. Created new `barbershops.js` API
![Снимок экрана 2023-08-23 в 10 37 53](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/569b7a36-79aa-4d1b-9114-50b2d48525dd)

2. Implemented data fetching in `src/app/page.tsx` file
![Снимок экрана 2023-08-23 в 10 38 32](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/b5b007d0-0d69-4e90-9c04-6760fbb83075)

3. Add props in `HeaderPage`, `Promo` components
![Снимок экрана 2023-08-23 в 10 46 39](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/898ccabb-ab8d-42fb-a965-5afb3e587fd9)
![Снимок экрана 2023-08-23 в 10 46 22](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/21490efe-38be-4470-a8a7-c35a119909ec)

4. Changed type of props in `Promobanner` component
![Снимок экрана 2023-08-23 в 10 47 13](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/1c1cc607-a90c-4f63-a582-892789d70fad)

5. Edit tests

2023-08-24 07:15 UTC, Alex-2kZharkov requested changes

2023-08-24 07:15 UTC, Alex-2kZharkov commented on src/app/page.tsx
> +  const numberOfBarbershops = JSON.stringify(jsonResponse.data);
You don't need additional step with JSON.stringify. See this check:

![Uploading image.png…]()

2023-08-25 05:25 UTC, ain-odin commented on src/app/page.tsx
> +  const numberOfBarbershops = JSON.stringify(jsonResponse.data);
The image you attached isn't shown, but I realize I was overcomplicated. Fixed it 
<img width="597" alt="Снимок экрана 2023-08-25 в 11 25 27" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/7dc9329f-34c6-4fac-83ee-b63d448d83d8">

2023-08-28 08:41 UTC, Alex-2kZharkov approved these changes

2023-08-28 11:23 UTC, merged