Feature/ob 23 layout cities modal
Alex-2kZharkov/oldboy-barbershop pull request #29
Opened 2023-08-24 07:14 UTC by Alinochka07

needs your review

2023-08-24 08:42 UTC, Alinochka07 commented
now I fixed errors with passing checks. Also, I couldn't resolve the problem of disabling main page's scrolling when the modal window is open. using overflow-hidden didn't help.

2023-08-24 14:00 UTC, Alex-2kZharkov requested changes

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/LocationSelectorScroll/LocationSelectorScroll.tsx
> +  locationLetter?: string;
Remove `locaiton` prefix, it does not add any value https://github.com/ryanmcdermott/clean-code-javascript#dont-add-unneeded-context

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/LocationSelectorScroll/LocationSelectorScroll.tsx
> +export interface LocationSelectorProps extends PropsWithChildren {
Again🤐 LocationSelectorProps => LocationSelectorScrollProps - almost full match to component name, besides Props ending

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/LocationSelector.tsx
The folder name RegionaSelect and the component name LocationSelector should match each other, please select 1

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/Russia/index.ts
you forgot to add reexport

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/LocationSelector.tsx
Don't forget to add index.ts file

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/Russia/RussianCitiesSelect.tsx
> +const alphabet = [
I have another suggestion. Alphabet should be a separate array like ['А', "Б"] etc. Then you will also have list of object with `city` and `address` as you have now. You can check that city belongs to letter like so:

```
city.startsWith(letter) - where letter is a letter from the array
```

I think we will need 2 nested loops here

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/Russia/RussianCitiesSelect.tsx
If you implement to comment above about separating alphabet and list of addresses, then it won't be just for Russia, it will be a reusable component

2023-08-24 14:00 UTC, Alex-2kZharkov commented on src/components/RegionSelect/Russia/RussianCitiesSelect.tsx
> +export const RussianLocationScroll = (): ReactElement => {
only 1 component per file, this should be moved to a separate folder (don;'t forget index.ts)

2023-08-25 04:15 UTC, Alinochka07 commented on src/components/LocationSelectorScroll/LocationSelectorScroll.tsx
> +  locationLetter?: string;
Sorry, you were constantly mentioning about it but despite I made the same mistake. Now, I got it.

2023-08-30 17:23 UTC, Alinochka07 commented
now cities and letters with the same name are limited to be displayed only once. Code works perfectly, the only issue is that it throws error of place and metro, since some values don't exist in some objects.

2023-09-03 06:02 UTC, Alex-2kZharkov approved these changes

2023-09-04 10:58 UTC, merged