renamed the Features folder and corrected the pathes
Alex-2kZharkov/oldboy-barbershop pull request #38
Opened 2023-09-11 12:03 UTC by bubumariia

2023-09-11 12:04 UTC, bubumariia commented
![localhost_3000_ (3)](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/99597584/56481b2c-763f-457c-985b-9e247bb30d69)

2023-09-11 12:05 UTC, bubumariia commented
it looks fine and no errors on console

2023-09-13 07:50 UTC, ain-odin commented on src/app/page.tsx
>  import { PromoCard } from '../components/PromoCard';
It seems the folder name is still the same
<img width="316" alt="Screenshot 2023-09-13 at 09 55 13" src="https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/119830208/0d8b5ed5-3fd6-42a3-825d-5a2242869852">
This is why the checks have not been successful.

2023-09-15 04:29 UTC, Alex-2kZharkov commented on src/app/page.tsx
>  import { PromoCard } from '../components/PromoCard';
yes, you are right Ainura.

@bubumariia you need to rename the folder itself. Click on the folder using the right button of your mouse, look for the `Rename` command if you are on the vs code (or google other ways to do it), For now, you've just renamed the occurrences of that folder, not the folder itself

2023-09-15 04:35 UTC, Alex-2kZharkov requested changes
waiting for the changes

2023-09-15 08:45 UTC, bubumariia commented
![dccab980-50cc-4ef3-b52e-8c7a03157533](https://github.com/Alex-2kZharkov/oldboy-barbershop/assets/99597584/b1485f59-af11-4b82-9b8b-a534c75015fa)

Actually, I have renamed it, I don't know why it is happening. Locally, as you can see it is lowercase.

2023-09-15 08:48 UTC, bubumariia commented
Let me find out what causes it

2023-09-19 08:33 UTC, closed without merging