feature_OB-5_Airbnb-eslint-packages
Alex-2kZharkov/oldboy-barbershop pull request #8
Opened 2023-07-16 13:07 UTC by bubumariia

added airbnb eslint packages

2023-07-18 18:21 UTC, Alex-2kZharkov commented
@bubumariia Ok, you have added packages to `package.json`, but they won't work automatically. You need to upgrade your `eslintrc` file, please see task description. Otherwise, this won't work

2023-07-18 18:21 UTC, Alex-2kZharkov requested changes
see comment above

2023-07-20 19:55 UTC, Alex-2kZharkov approved these changes, later dismissed

2023-07-21 08:24 UTC, MillanaCh approved these changes

2023-07-21 08:25 UTC, merged